//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second_Electricity_POC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emnployee
    {
        public int ID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> LeaveBalance { get; set; }
        public string LineManagerRemark { get; set; }
        public string HRRemark { get; set; }
        public Nullable<int> RequestId { get; set; }
    
        public virtual GeneralRequest GeneralRequest { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
