//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second_Electricity_POC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarManagement
    {
        public int ID { get; set; }
        public string LineManagerRemark { get; set; }
        public string HRRemark { get; set; }
    }
}
