//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second_Electricity_POC.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri2.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="K2TaskItem", Namespace="http://tempuri2.org/")]
    [System.SerializableAttribute()]
    public partial class K2TaskItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Second_Electricity_POC.ServiceReference.ArrayOfString ActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessInstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalEmployeeNameWithPrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameEnField;
        
        private System.DateTime RequestDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Second_Electricity_POC.ServiceReference.ArrayOfString Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionsField, value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.serialNumberField, value) != true)) {
                    this.serialNumberField = value;
                    this.RaisePropertyChanged("serialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessInstanceId {
            get {
                return this.ProcessInstanceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessInstanceIdField, value) != true)) {
                    this.ProcessInstanceIdField = value;
                    this.RaisePropertyChanged("ProcessInstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TaskLink {
            get {
                return this.TaskLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskLinkField, value) != true)) {
                    this.TaskLinkField = value;
                    this.RaisePropertyChanged("TaskLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TaskStatus {
            get {
                return this.TaskStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskStatusField, value) != true)) {
                    this.TaskStatusField = value;
                    this.RaisePropertyChanged("TaskStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TaskOwner {
            get {
                return this.TaskOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskOwnerField, value) != true)) {
                    this.TaskOwnerField = value;
                    this.RaisePropertyChanged("TaskOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string InternalEmployeeNameWithPrefix {
            get {
                return this.InternalEmployeeNameWithPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalEmployeeNameWithPrefixField, value) != true)) {
                    this.InternalEmployeeNameWithPrefixField = value;
                    this.RaisePropertyChanged("InternalEmployeeNameWithPrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string EmployeeNameEn {
            get {
                return this.EmployeeNameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameEnField, value) != true)) {
                    this.EmployeeNameEnField = value;
                    this.RaisePropertyChanged("EmployeeNameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DepartmentNameEn {
            get {
                return this.DepartmentNameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameEnField, value) != true)) {
                    this.DepartmentNameEnField = value;
                    this.RaisePropertyChanged("DepartmentNameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string InternalServiceName {
            get {
                return this.InternalServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalServiceNameField, value) != true)) {
                    this.InternalServiceNameField = value;
                    this.RaisePropertyChanged("InternalServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ServiceNameEn {
            get {
                return this.ServiceNameEnField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameEnField, value) != true)) {
                    this.ServiceNameEnField = value;
                    this.RaisePropertyChanged("ServiceNameEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri2.org/", ConfigurationName="ServiceReference.TaskActionSoap")]
    public interface TaskActionSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/TaskActionsList", ReplyAction="*")]
        Second_Electricity_POC.ServiceReference.TaskActionsListResponse TaskActionsList(Second_Electricity_POC.ServiceReference.TaskActionsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/TaskActionsList", ReplyAction="*")]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.TaskActionsListResponse> TaskActionsListAsync(Second_Electricity_POC.ServiceReference.TaskActionsListRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/StartProcess", ReplyAction="*")]
        Second_Electricity_POC.ServiceReference.StartProcessResponse StartProcess(Second_Electricity_POC.ServiceReference.StartProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/StartProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.StartProcessResponse> StartProcessAsync(Second_Electricity_POC.ServiceReference.StartProcessRequest request);
        
        // CODEGEN: Generating message contract since element name serialNumber from namespace http://tempuri2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/ActionWorklistItem", ReplyAction="*")]
        Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse ActionWorklistItem(Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/ActionWorklistItem", ReplyAction="*")]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse> ActionWorklistItemAsync(Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest request);
        
        // CODEGEN: Generating message contract since element name userNameWithPrefix from namespace http://tempuri2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/GetEmployeeTaskList", ReplyAction="*")]
        Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse GetEmployeeTaskList(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri2.org/GetEmployeeTaskList", ReplyAction="*")]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse> GetEmployeeTaskListAsync(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TaskActionsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TaskActionsList", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.TaskActionsListRequestBody Body;
        
        public TaskActionsListRequest() {
        }
        
        public TaskActionsListRequest(Second_Electricity_POC.ServiceReference.TaskActionsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class TaskActionsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string serialNumber;
        
        public TaskActionsListRequestBody() {
        }
        
        public TaskActionsListRequestBody(string userName, string serialNumber) {
            this.userName = userName;
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TaskActionsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TaskActionsListResponse", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.TaskActionsListResponseBody Body;
        
        public TaskActionsListResponse() {
        }
        
        public TaskActionsListResponse(Second_Electricity_POC.ServiceReference.TaskActionsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class TaskActionsListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Second_Electricity_POC.ServiceReference.ArrayOfString TaskActionsListResult;
        
        public TaskActionsListResponseBody() {
        }
        
        public TaskActionsListResponseBody(Second_Electricity_POC.ServiceReference.ArrayOfString TaskActionsListResult) {
            this.TaskActionsListResult = TaskActionsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcess", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.StartProcessRequestBody Body;
        
        public StartProcessRequest() {
        }
        
        public StartProcessRequest(Second_Electricity_POC.ServiceReference.StartProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class StartProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int TableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int GeneralRequesID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProcessName;
        
        public StartProcessRequestBody() {
        }
        
        public StartProcessRequestBody(string userName, int TableID, int GeneralRequesID, string ProcessName) {
            this.userName = userName;
            this.TableID = TableID;
            this.GeneralRequesID = GeneralRequesID;
            this.ProcessName = ProcessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartProcessResponse", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.StartProcessResponseBody Body;
        
        public StartProcessResponse() {
        }
        
        public StartProcessResponse(Second_Electricity_POC.ServiceReference.StartProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class StartProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int StartProcessResult;
        
        public StartProcessResponseBody() {
        }
        
        public StartProcessResponseBody(int StartProcessResult) {
            this.StartProcessResult = StartProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActionWorklistItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActionWorklistItem", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.ActionWorklistItemRequestBody Body;
        
        public ActionWorklistItemRequest() {
        }
        
        public ActionWorklistItemRequest(Second_Electricity_POC.ServiceReference.ActionWorklistItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class ActionWorklistItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userNameWithPrefix;
        
        public ActionWorklistItemRequestBody() {
        }
        
        public ActionWorklistItemRequestBody(string serialNumber, string action, string userNameWithPrefix) {
            this.serialNumber = serialNumber;
            this.action = action;
            this.userNameWithPrefix = userNameWithPrefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActionWorklistItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActionWorklistItemResponse", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.ActionWorklistItemResponseBody Body;
        
        public ActionWorklistItemResponse() {
        }
        
        public ActionWorklistItemResponse(Second_Electricity_POC.ServiceReference.ActionWorklistItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class ActionWorklistItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActionWorklistItemResult;
        
        public ActionWorklistItemResponseBody() {
        }
        
        public ActionWorklistItemResponseBody(bool ActionWorklistItemResult) {
            this.ActionWorklistItemResult = ActionWorklistItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTaskListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTaskList", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequestBody Body;
        
        public GetEmployeeTaskListRequest() {
        }
        
        public GetEmployeeTaskListRequest(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class GetEmployeeTaskListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNameWithPrefix;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string searchPattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string employeeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string employeeNameEn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string departmentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string departmentNameEn;
        
        public GetEmployeeTaskListRequestBody() {
        }
        
        public GetEmployeeTaskListRequestBody(string userNameWithPrefix, string searchPattern, string employeeName, string employeeNameEn, string departmentName, string departmentNameEn) {
            this.userNameWithPrefix = userNameWithPrefix;
            this.searchPattern = searchPattern;
            this.employeeName = employeeName;
            this.employeeNameEn = employeeNameEn;
            this.departmentName = departmentName;
            this.departmentNameEn = departmentNameEn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeTaskListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeTaskListResponse", Namespace="http://tempuri2.org/", Order=0)]
        public Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponseBody Body;
        
        public GetEmployeeTaskListResponse() {
        }
        
        public GetEmployeeTaskListResponse(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri2.org/")]
    public partial class GetEmployeeTaskListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Second_Electricity_POC.ServiceReference.K2TaskItem[] GetEmployeeTaskListResult;
        
        public GetEmployeeTaskListResponseBody() {
        }
        
        public GetEmployeeTaskListResponseBody(Second_Electricity_POC.ServiceReference.K2TaskItem[] GetEmployeeTaskListResult) {
            this.GetEmployeeTaskListResult = GetEmployeeTaskListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TaskActionSoapChannel : Second_Electricity_POC.ServiceReference.TaskActionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskActionSoapClient : System.ServiceModel.ClientBase<Second_Electricity_POC.ServiceReference.TaskActionSoap>, Second_Electricity_POC.ServiceReference.TaskActionSoap {
        
        public TaskActionSoapClient() {
        }
        
        public TaskActionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskActionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskActionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskActionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Second_Electricity_POC.ServiceReference.TaskActionsListResponse Second_Electricity_POC.ServiceReference.TaskActionSoap.TaskActionsList(Second_Electricity_POC.ServiceReference.TaskActionsListRequest request) {
            return base.Channel.TaskActionsList(request);
        }
        
        public Second_Electricity_POC.ServiceReference.ArrayOfString TaskActionsList(string userName, string serialNumber) {
            Second_Electricity_POC.ServiceReference.TaskActionsListRequest inValue = new Second_Electricity_POC.ServiceReference.TaskActionsListRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.TaskActionsListRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.serialNumber = serialNumber;
            Second_Electricity_POC.ServiceReference.TaskActionsListResponse retVal = ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).TaskActionsList(inValue);
            return retVal.Body.TaskActionsListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.TaskActionsListResponse> Second_Electricity_POC.ServiceReference.TaskActionSoap.TaskActionsListAsync(Second_Electricity_POC.ServiceReference.TaskActionsListRequest request) {
            return base.Channel.TaskActionsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.TaskActionsListResponse> TaskActionsListAsync(string userName, string serialNumber) {
            Second_Electricity_POC.ServiceReference.TaskActionsListRequest inValue = new Second_Electricity_POC.ServiceReference.TaskActionsListRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.TaskActionsListRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.serialNumber = serialNumber;
            return ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).TaskActionsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Second_Electricity_POC.ServiceReference.StartProcessResponse Second_Electricity_POC.ServiceReference.TaskActionSoap.StartProcess(Second_Electricity_POC.ServiceReference.StartProcessRequest request) {
            return base.Channel.StartProcess(request);
        }
        
        public int StartProcess(string userName, int TableID, int GeneralRequesID, string ProcessName) {
            Second_Electricity_POC.ServiceReference.StartProcessRequest inValue = new Second_Electricity_POC.ServiceReference.StartProcessRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.StartProcessRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.TableID = TableID;
            inValue.Body.GeneralRequesID = GeneralRequesID;
            inValue.Body.ProcessName = ProcessName;
            Second_Electricity_POC.ServiceReference.StartProcessResponse retVal = ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).StartProcess(inValue);
            return retVal.Body.StartProcessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.StartProcessResponse> Second_Electricity_POC.ServiceReference.TaskActionSoap.StartProcessAsync(Second_Electricity_POC.ServiceReference.StartProcessRequest request) {
            return base.Channel.StartProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.StartProcessResponse> StartProcessAsync(string userName, int TableID, int GeneralRequesID, string ProcessName) {
            Second_Electricity_POC.ServiceReference.StartProcessRequest inValue = new Second_Electricity_POC.ServiceReference.StartProcessRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.StartProcessRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.TableID = TableID;
            inValue.Body.GeneralRequesID = GeneralRequesID;
            inValue.Body.ProcessName = ProcessName;
            return ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).StartProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse Second_Electricity_POC.ServiceReference.TaskActionSoap.ActionWorklistItem(Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest request) {
            return base.Channel.ActionWorklistItem(request);
        }
        
        public bool ActionWorklistItem(string serialNumber, string action, string userNameWithPrefix) {
            Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest inValue = new Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.ActionWorklistItemRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.action = action;
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse retVal = ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).ActionWorklistItem(inValue);
            return retVal.Body.ActionWorklistItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse> Second_Electricity_POC.ServiceReference.TaskActionSoap.ActionWorklistItemAsync(Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest request) {
            return base.Channel.ActionWorklistItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.ActionWorklistItemResponse> ActionWorklistItemAsync(string serialNumber, string action, string userNameWithPrefix) {
            Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest inValue = new Second_Electricity_POC.ServiceReference.ActionWorklistItemRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.ActionWorklistItemRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.action = action;
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            return ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).ActionWorklistItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse Second_Electricity_POC.ServiceReference.TaskActionSoap.GetEmployeeTaskList(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest request) {
            return base.Channel.GetEmployeeTaskList(request);
        }
        
        public Second_Electricity_POC.ServiceReference.K2TaskItem[] GetEmployeeTaskList(string userNameWithPrefix, string searchPattern, string employeeName, string employeeNameEn, string departmentName, string departmentNameEn) {
            Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest inValue = new Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequestBody();
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            inValue.Body.searchPattern = searchPattern;
            inValue.Body.employeeName = employeeName;
            inValue.Body.employeeNameEn = employeeNameEn;
            inValue.Body.departmentName = departmentName;
            inValue.Body.departmentNameEn = departmentNameEn;
            Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse retVal = ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).GetEmployeeTaskList(inValue);
            return retVal.Body.GetEmployeeTaskListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse> Second_Electricity_POC.ServiceReference.TaskActionSoap.GetEmployeeTaskListAsync(Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest request) {
            return base.Channel.GetEmployeeTaskListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Second_Electricity_POC.ServiceReference.GetEmployeeTaskListResponse> GetEmployeeTaskListAsync(string userNameWithPrefix, string searchPattern, string employeeName, string employeeNameEn, string departmentName, string departmentNameEn) {
            Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest inValue = new Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequest();
            inValue.Body = new Second_Electricity_POC.ServiceReference.GetEmployeeTaskListRequestBody();
            inValue.Body.userNameWithPrefix = userNameWithPrefix;
            inValue.Body.searchPattern = searchPattern;
            inValue.Body.employeeName = employeeName;
            inValue.Body.employeeNameEn = employeeNameEn;
            inValue.Body.departmentName = departmentName;
            inValue.Body.departmentNameEn = departmentNameEn;
            return ((Second_Electricity_POC.ServiceReference.TaskActionSoap)(this)).GetEmployeeTaskListAsync(inValue);
        }
    }
}
